

- name: Post license key
  uri:
    url: https://localhost/api/v2/config/
    method: POST
    user: admin
    password: "{{ towerpass }}"
    body: "{{ lookup('file','tower_license.json') }}"
    body_format: json
    validate_certs: False

 
- name: Add Subscription to RHEL
  redhat_subscription:
    state: present
    username: "{{ subscription_user }}" 
    password: "{{ subscription_pass }}" 
    auto_attach: true

- name: Enable RHSCL repository
  rhsm_repository:
    name: rhel-server-rhscl-7-rpms
 
- name: install pip
  yum:
    name: python27-python-pip
    state: present
    
- name: Copy Tower Module File
  get_url: 
    url: https://raw.githubusercontent.com/vsylvest/Tower-Config/master/roles/tower/files/Install-Modules
    dest: /home/student1/install_modules.sh
    owner: awx
    group: awx
    mode: 0755 
    
- name: Install Modules
  shell: /home/student1/./install_modules.sh
    
- name: Copy Tower Config File
  get_url: 
    url: https://raw.githubusercontent.com/vsylvest/Tower-Config/master/roles/tower/files/Config_Tower
    dest: /home/student1/configure_tower.sh
    owner: awx
    group: awx
    mode: 0755 

- name: Configure Tower
  shell: /home/student1/./configure_tower.sh
  ignore_errors: yes