fields:
  - type: string
    id: username
    label: Username
  - type: string
    id: password
    label: Password
    secret: true
  - type: string
    id: instance
    label: instance
required:
  - username
  - password
  - instance